import type { Metadata } from "next";
import { Zen_Kaku_Gothic_New,Outfit} from "next/font/google";
import "@/styles/global.scss"
import Header from "@/components/layout/Header";
const ZenKakuGothicNewFont = Zen_Kaku_Gothic_New({
   weight: ["400","500","700"],
  subsets: ["latin"],
   variable: "--font-zenkaku-gothic-new",
   display: 'swap',
   preload:true,
});

const OutfitFont = Outfit({
   weight: "700",
  subsets: ["latin"],
   variable: "--font-outfit",
   display: 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={`${ZenKakuGothicNewFont.variable} ${OutfitFont.variable}`}>
      <body >
      <Header/>
        {children}
      </body>
    </html>
  );
}
